services:
  - name: formio-app
    type: web
    env: docker
    repo: https://github.com/formio/formio
    branch: master
    plan: starter
    buildCommand: ""
    startCommand: ""
    dockerfilePath: Dockerfile
    autoDeploy: true
    envVars:
      - key: MONGO_URI
        fromDatabase:
          name: formio-db
          property: connectionString
      - key: JWT_SECRET
        value: "<ton-secret-jwt-manuellement>" # Défini manuellement ou via l'interface Render
      - key: ADMIN_EMAIL
        value: "admin@example.com"
      - key: ADMIN_PASSWORD
        value: "<ton-mot-de-passe-admin-manuellement>" # Défini manuellement ou via l'interface Render
databases:
  - name: formio-db
    type: mongodb
    plan: free
    ipAllowList: []
